"""Bake a bitmap font into the renderer.

The drawing must be identical between the native test build and WebAssembly,
so no browser text and no platform font API: glyphs are rasterised once, here,
and committed as data.  DejaVu Sans is the source - a Bitstream Vera
derivative whose licence permits redistribution, shipped with matplotlib so
nothing is downloaded.

Camera numbers are two digits, panel text is ASCII: 0x20..0x7E at three
sizes.  Eight-bit alpha per pixel (the renderer blends it), rows packed
per glyph, all glyphs of one size sharing a common cell height and baseline.

Output is a C++ header: src/font_data.h.
"""

import os

import matplotlib
from PIL import Image, ImageDraw, ImageFont

SIZES = [12, 16, 24]
FIRST = 0x20
LAST = 0x7E

FONT = os.path.join(os.path.dirname(matplotlib.__file__),
                    'mpl-data', 'fonts', 'ttf', 'DejaVuSans.ttf')
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   '..', 'src', 'font_data.h')


def bake(size):
    font = ImageFont.truetype(FONT, size)
    ascent, descent = font.getmetrics()
    cell_h = ascent + descent
    glyphs = []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        advance = int(round(font.getlength(ch)))
        w = max(advance, 1)
        img = Image.new('L', (w + 4, cell_h), 0)
        ImageDraw.Draw(img).text((2, 0), ch, fill=255, font=font)
        # Trim horizontally to the inked box but keep the pen offset.
        bbox = img.getbbox()
        if bbox is None:
            glyphs.append((advance, 0, 0, 0, b''))
            continue
        x0, _, x1, _ = bbox
        left = x0 - 2                     # ink offset from the pen position
        gw = x1 - x0
        data = bytearray()
        for y in range(cell_h):
            for x in range(x0, x1):
                data.append(img.getpixel((x, y)))
        glyphs.append((advance, left, gw, cell_h, bytes(data)))
    return cell_h, ascent, glyphs


def main():
    parts = []
    parts.append('// Generated by tools/make_font.py - do not edit.\n')
    parts.append('// DejaVu Sans (Bitstream Vera licence), sizes %s.\n'
                 % ', '.join(str(s) for s in SIZES))
    parts.append('#pragma once\n#include <cstdint>\n\n')
    parts.append('struct FontGlyph { uint8_t advance; int8_t left; '
                 'uint8_t width; uint32_t offset; };\n')
    parts.append('struct FontSize { int height; int ascent; '
                 'const FontGlyph * glyphs; const uint8_t * pixels; };\n\n')

    for size in SIZES:
        cell_h, ascent, glyphs = bake(size)
        pixels = bytearray()
        table = []
        for advance, left, gw, gh, data in glyphs:
            table.append((advance, left, gw, len(pixels)))
            pixels.extend(data)
        parts.append('static const FontGlyph kGlyphs%d[%d] = {\n'
                     % (size, len(table)))
        for advance, left, gw, offset in table:
            parts.append('    {%d, %d, %d, %du},\n'
                         % (advance, left, gw, offset))
        parts.append('};\n')
        parts.append('static const uint8_t kPixels%d[%d] = {\n'
                     % (size, max(len(pixels), 1)))
        for i in range(0, len(pixels), 24):
            parts.append('    ' + ','.join(str(b) for b in pixels[i:i+24])
                         + ',\n')
        if not pixels:
            parts.append('    0,\n')
        parts.append('};\n')
        parts.append('static const FontSize kFont%d = {%d, %d, kGlyphs%d, '
                     'kPixels%d};\n\n' % (size, cell_h, ascent, size, size))

    parts.append('static const FontSize * fontForHeight(int px) {\n')
    parts.append('    if (px >= %d) return &kFont%d;\n' % (SIZES[-1], SIZES[-1]))
    parts.append('    if (px >= %d) return &kFont%d;\n' % (SIZES[1], SIZES[1]))
    parts.append('    return &kFont%d;\n}\n' % SIZES[0])

    with open(OUT, 'w') as f:
        f.write(''.join(parts))
    print('wrote', os.path.normpath(OUT))


if __name__ == '__main__':
    main()
